import './globals.css';

import '@appwrite.io/pink';
import '@appwrite.io/pink-icons';

import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import {UserProvider} from '@/hooks/useUser';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<UserProvider>
				<body className={inter.className}>{children}</body>
			</UserProvider>
		</html>
	);
}
